ALTER TABLE users
DROP INDEX unique_username,
DROP INDEX unique_email;
ALTER TABLE players
MODIFY COLUMN Player VARCHAR(255) NOT NULL,
MODIFY COLUMN Position VARCHAR(255) NOT NULL,
MODIFY COLUMN team_id VARCHAR(255) NOT NULL;
ALTER TABLE teams
MODIFY COLUMN team_name VARCHAR(255) NOT NULL,
MODIFY COLUMN city VARCHAR(255) NOT NULL;